

version: '3.1'
services:

  apache:
    build: ./api/
    container_name: ${CONTAINER_NAME}
    ports:
      - "${LARAVEL_APP_PORT}:80"
      - "${ANGULAR_APP_PORT}:4200"
    volumes:
      - ./config/vhosts_enabled:/etc/apache2/sites-enabled
      - ./config/vhosts_available:/etc/apache2/sites-available
      - ${DOCKER_APP_VOLUME:-../}:/var/www/html
    expose:
        - "4200"

  mysql:
    image: mysql:5.7
    container_name: larv5_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}